### PR TITLE
Reorganize screenshots & screencasts

### PR DESCRIPTION
**Pull request by Symbian9**

### CODE REVIEW

**Comment by artem78** [comment]
1) Why did you choose "About" screenshot as main, but not any other?
2) I think that one of gifs is redundant. Maybe it will be better to delete the first one?

**Comment by Symbian9** [comment]
> 1. Why did you choose "About" screenshot as main, but not any other?

Because "About" dialog is main info of the app.

The rest of the screens are just showcases which should be moved to "Screenshots" sub-section.

**Comment by Symbian9** [comment]
> I think that one of gifs is redundant. Maybe it will be better to delete the first one?

Just removed this redundant gif from readme & updated Markdown.

**Comment by artem78** [comment]
@Symbian9 Good work!

**Comment by artem78** [comment]
Why your uppercased these 3 headers: DOWNLOAD, ROADMAP and LICENSE?

**Comment by artem78** [comment]
Could you also help me to improve ReadMe in [another symbian project](https://github.com/artem78/s60-gps-tracker)?

**Pull request merged**
