### PR TITLE
Hebrew translation.

### PR DESCRIPTION
**Pull request by Men770**
I translated all the strings into Hebrew.

### CODE REVIEW

**Comment by artem78** [comment]
Thanks. I will make build later, so you can check that translation works fine.

**Comment by artem78** [comment]
I make build with Hebrew. Test it - [S60Maps test hebrew.zip](https://github.com/artem78/s60-maps/files/5754337/S60Maps.test.hebrew.zip).

If your phone language is Hebrew, you will see all UI translated.

**Comment by artem78** [comment]
I taked screenshots of translated UI: 
[hebrew screenshots.zip](https://github.com/artem78/s60-maps/files/5754742/hebrew.screenshots.zip)
You may check them.

**Comment by Men770** [comment]
@artem78 Works great.
Thanks.

**Comment by artem78** [comment]
Good.

**Comment by artem78** [comment]
@Men770 Could you please update your translation?

https://github.com/artem78/s60-maps/compare/v1.3.0...develop?diff=split#diff-16e77c5ffb7162e7917b78eca7e42e08f1c1f8fd5b4ed7eddd36331c2dac6f68

Thank you.

**Pull request merged**
