### PR TITLE
Go to landmark

### PR DESCRIPTION
**Pull request by baranovskiykonstantin**

### CODE REVIEW

**Comment by artem78** [comment]
Wow! Interesting and usefull feature.

Initially I wished to make similar list of landmarks with edit/detele actions (like in Yandex Maps application). But then realized that it be more convenient to do this directly on the map.

Besides it will be a good idea to zoom to choosen landmark.

**Comment by baranovskiykonstantin** [comment]
Hi, @artem78 !
I'm going to add a couple of features/fixes related to the landmarks.
1. On touchscreen devices the center crosshair jumps around when the device orientation changes or when the softkays appear. The coordinate under the crosshair must remain unchanged in this cases, I think.
2. It would be great to move the "Go to..." item in the top menu pane and assign the submenu to it with two subitems:
* Landmark
* Coordinate

"Go to... -> Landmark" allows move to a landmark by selecting from the list dialog.
"Go to... -> Coordinate" allows move to a coordiate by entering latitude/longitude in custom query dialog.

Do you have any objections (especialy to the second item)?

**Comment by artem78** [comment]
Hi, @baranovskiykonstantin.

> I'm going to add a couple of features/fixes related to the landmarks.

Nice to hear that you are interested to make contribution to this project. I suggest you to make 2 separate pull requests - for **fixes** and for **new features**. I planned to publish v1.5.1 soon with fixes (mainly for landmarks) and add new features later.

> On touchscreen devices the center crosshair jumps around when the device orientation changes or when the softkays appear. The coordinate under the crosshair must remain unchanged in this cases, I think.

You are right. It will be better to fix this.

> "Go to... -> Coordinate" allows move to a coordiate by entering latitude/longitude in custom query dialog.

I think this is not really necessary, but if you want you may add this.

-----------

There is my list of TODOs:
- Delete landmark with **C** key
- Add or rename exists landmark with central key
- Show crosshair only when map moves and hide after a couple of seconds after
- Many landmarks look very messy:
   Snap3775

**Comment by baranovskiykonstantin** [comment]
I've separated the update-landmark-fix from this pull request.

**Comment by baranovskiykonstantin** [comment]
> 2. It would be great to move the "Go to..." item in the top menu pane and assign the submenu to it with two subitems:
> 
> * Landmark
> * Coordinate
> 
> "Go to... -> Landmark" allows move to a landmark by selecting from the list dialog.
> "Go to... -> Coordinate" allows move to a coordiate by entering latitude/longitude in custom query dialog.

I've just finished the implementation of this feature:
Scr000006 Scr000005

**Comment by artem78** [comment]
Hi, Konstantin!

I substantially increased list drawing speed for a large number of landmarks (hundreds). My wish is to add search. Could you make this?

Snap3890

**Comment by baranovskiykonstantin** [comment]
Hello, @artem78.
I have no time at the moment :( Maybe in the future.

**Comment by artem78** [comment]
@baranovskiykonstantin Okay!

**Comment by artem78** [comment]
> My wish is to add search. Could you make this?

I implemented this in #49.

**Comment by artem78** [comment]
Hi @baranovskiykonstantin !

Can you remake coordinates dialog to make it available also on Symbian 9.1?

**Pull request merged**
