### PR TITLE
Symbian S60 v5 support

### PR DESCRIPTION
**Pull request by baranovskiykonstantin**
Tested on Nokia 5530 XM

### CODE REVIEW

**Comment by artem78** [comment]
Thank you for contribution!

I will check and merge this later when I have time.

**Comment by artem78** [comment]
Hello Konstantin!

I just checked your changes. I didn\`t find any visible problems and ready to merge your pull request. I\`m sorry for waiting. I didn`t forget about you, but just had no free time.

I have no 5th edition phone and tested you code on emulator from SDK. I found out, that on emulator program icon looks strange with inexplicable black blots.

Bad on 5th ed.

Compared with v5, in v3 icon looks correct both on emulator and phone.

Good on 3rd ed.

Therefore I want to ask you to check how it looks on your v5 phone.

**Comment by baranovskiykonstantin** [comment]
Hi Artem!
I also noticed the emulator was showing the distorted icon but this problem does not appear on the device:
Scr000074

**Comment by artem78** [comment]
> this problem does not appear on the device:

Sounds good. Thank your for sceenshots.

**Pull request merged**
