### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Symbian9**
- Remove duplicated mentions
- Add links to Wikipedia
- Improve docs style
- Smartphone (instead of phone/mobile)

### CODE REVIEW

**Comment by artem78** [comment]
You are perfectionist!

**Comment by artem78** [comment]
What about [this](https://github.com/artem78/s60-maps/pull/8#issuecomment-748601756)? Could you make them as others?

**Comment by Symbian9** [comment]
> What about this?

Okay, I would lowercase Download & Roadmap.

But LICENSE, as it is major info of the opensource project, should left uppercased.

**Comment by artem78** [comment]
> But LICENSE, as it is major info of the opensource project, should left uppercased.

Okay

**Comment by artem78** [comment]
Is [this info](https://digipassion.com/signing-sissisx-files-for-symbian-s60/) is still actual?

**Comment by Symbian9** [comment]
> Is this info is still actual?

Yes, as 2nd (offline) method still works!

BTW, If I would find better (more actual) guide, I will update/replace actual guide link.

**Pull request merged**
