### PR TITLE
 Latin American Spanish translation

### PR DESCRIPTION
**Pull request by huhungahuru**

### CODE REVIEW

**Comment by artem78** [comment]
Thank you, but I have already Spanish translation created by another person. But I didn\`t add it to last realease or to GitHub yet.

**Comment by artem78** [comment]
Maybe you can help with another language?

**Comment by artem78** [comment]
> I have already Spanish translation created by another person

Maybe I jumped the gun with decline your pull request. I have already [Spanish (id=4)](https://github.com/artem78/s60-maps/blob/a0cd7c28559fdba3051a2ea0bc17eb610ec30335/data/S60Maps.l04), but your localization for **American** Spanish (id=83). If they are different, I can add your localization too.

**Comment by artem78** [comment]
@huhungahuru Could you please update your translation?

Changes: https://github.com/artem78/s60-maps/compare/v1.3.0...develop?diff=split#diff-16e77c5ffb7162e7917b78eca7e42e08f1c1f8fd5b4ed7eddd36331c2dac6f68

Thank you.

**Comment by huhungahuru** [comment]
Translation update for 1.4.0

**Comment by artem78** [comment]
Next time please make pull request to **develop** branch.

**Comment by artem78** [comment]
Hello @huhungahuru.

I need your help with translation again. Could you please translate [these strings](https://github.com/artem78/s60-maps/compare/v1.4.0...develop#diff-44c6ca30c424e68f37d13466cd73b33ffd01dac77278a0da586f9f66fc23a377) and make pull request to [develop](https://github.com/artem78/s60-maps/tree/develop) branch?

Many thanks.

**Comment by artem78** [comment]
Hi!

Some new strings update needed:
[https://github.com/artem78/s60-maps/blob/develop/data/S60Maps.l83#L59-L63](https://github.com/artem78/s60-maps/blob/develop/data/S60Maps.l83#L59-L63)

**Pull request merged**
